# This workflow integrates ShiftLeft with GitHub
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft

on:
  pull_request:
  workflow_dispatch:

jobs:
  Inspect-Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Analyze
      run: ${GITHUB_WORKSPACE}/sl analyze --app ShiftLeftTerraform --tag branch=${GITHUB_REF} --terraform $(pwd)
      env:
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}
